name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          working-directory: ./front-page

      - name: Install dependencies
        run: npm install
        working-directory: ./front-page

      - name: Build project
        run: npm run build
        working-directory: ./front-page

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUD_FLARE_DEPLOY_API_TOKEN }}
          accountId: ${{ secrets.CLOUD_FLARE_DEPLOY_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: ./front-page/dist
